packages:
  - "."

overrides:
  "@types/react": "19.2.14"
  "@types/react-dom": "19.2.3"

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - postcss@8.5.10
  - uuid@11.1.1
  - '@babel/core@7.29.1'
  - js-yaml@4.1.2
